# refresh token with $> firebase login:ci

name: CI
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GETSIZE_27A43 }}"
          channelId: live
          projectId: getsize-27a43
